name: deploye
on: push
branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -name: get code
       -uses: actions/checkout@v3
      -name: single line code
      run: echo "testing"

      

